### PR TITLE
Support Ruby 3.1

### PR DESCRIPTION
**Pull request by dcermak**

### CODE REVIEW

**Comment by pvalena** [comment]
In Fedora, this fails with following: 
```
+ vagrant status
/usr/share/rubygems/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies': undefined method `request' for nil:NilClass (NoMethodError)

    [@failed_dep.dependency, @activated.request.dependency]
                                       ^^^^^^^^
        from /usr/share/rubygems/rubygems/exceptions.rb:61:in `conflicting_dependencies'
        from /usr/share/rubygems/rubygems/exceptions.rb:55:in `initialize'
        from /usr/share/rubygems/rubygems/resolver.rb:193:in `exception'
        from /usr/share/rubygems/rubygems/resolver.rb:193:in `raise'
        from /usr/share/rubygems/rubygems/resolver.rb:193:in `rescue in resolve'
        from /usr/share/rubygems/rubygems/resolver.rb:191:in `resolve'
        from /usr/share/rubygems/rubygems/request_set.rb:411:in `resolve'
        from /usr/share/rubygems/rubygems/request_set.rb:423:in `resolve_current'
        from /usr/share/rubygems/rubygems.rb:230:in `finish_resolve'
        from /usr/share/rubygems/rubygems.rb:287:in `block in activate_bin_path'
        from /usr/share/rubygems/rubygems.rb:285:in `synchronize'
        from /usr/share/rubygems/rubygems.rb:285:in `activate_bin_path'
        from /usr/share/vagrant/gems/bin/vagrant:25:in `<main>'
/usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317:in `raise_error_unless_state': Unable to satisfy the following requirements: (Gem::Resolver::Molinillo::VersionConflict)

- `vagrant (= 2.2.19)` required by `user-specified dependency`
        from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
        from <internal:kernel>:90:in `tap'
        from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
        from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
        from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
        from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
        from /usr/share/rubygems/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
        from /usr/share/rubygems/rubygems/resolver.rb:190:in `resolve'
        from /usr/share/rubygems/rubygems/request_set.rb:411:in `resolve'
        from /usr/share/rubygems/rubygems/request_set.rb:423:in `resolve_current'
        from /usr/share/rubygems/rubygems.rb:230:in `finish_resolve'
        from /usr/share/rubygems/rubygems.rb:287:in `block in activate_bin_path'
        from /usr/share/rubygems/rubygems.rb:285:in `synchronize'
        from /usr/share/rubygems/rubygems.rb:285:in `activate_bin_path'
        from /usr/share/vagrant/gems/bin/vagrant:25:in `<main>'
```

**Comment by dcermak** [comment]
> I suspect the API has changed. Do you have any WIP fix or idea on how to fix it?

Unfortunately no, as I haven't observed this failure on openSUSE Tumbleweed, where we've been running vagrant with Ruby 3.1 for a while now.

**Comment by pvalena** [comment]
@jackorp  any progress?

**Comment by jackorp** [comment]
> @jackorp any progress?

The latest info is: clean upstream ruby v3_1_0 works, removing the restriction `"< 3.1"` for `required_ruby_version` from gemspec works as well, with the package AFAICT... I'll investigate more closely now and try to pinpoint the issue.

**Comment by jackorp** [comment]
If we are talking about the distro's vagrant, installed with `zypper install vagrant`, then it works (and it does not throw the exception as described [in previous comment by pvalena](https://github.com/hashicorp/vagrant/pull/12638#issuecomment-1046911601)) because the gemspec is patched to allow for Ruby 3.1 in the required_ruby_version.

**Comment by dcermak** [comment]
@chrisroberts Could you please take a look?

**Comment by dcermak** [comment]
@chrisroberts @soapy1 @phinze Could you please take a look? Ruby 3.1 is the default on many distributions now and this is now starting to block development with vagrant on these…

**Comment by dcermak** [comment]
@soapy1 Can you please take a look?

**Review by chrisroberts — APPROVED** [review]

**Pull request merged**
