### PR TITLE
Update usage.mdx

### PR DESCRIPTION
**Pull request by wschoot**
Typo in docs

### CODE REVIEW

**Review by soapy1 — APPROVED** [review]
Thanks!

**Comment by wschoot** [comment]
https://github.com/hashicorp/vagrant/search?q=reqiures

Seems this happens more than once. Want me to add to this PR?

**Comment by soapy1** [comment]
@wschoot thanks for finding that! You can open up a new PR if you like 😃

**Comment by wschoot** [comment]
Got it! (https://github.com/hashicorp/vagrant/pull/12170)

**Pull request merged**
