### PR TITLE
@ #10460 | fix vagrant rsync-auto is crashed

### PR DESCRIPTION
**Pull request by hieptranquoc**
connect #10460 
Please check this PR! Thank you so much! 
Explain: 
```
"find #{guest_path} #{exclusions}" \
          "'!' -type l -a " \
          "'(' ! -user #{opts[:owner]} -or ! -group #{opts[:group]} ')' -exec " \
          "chown #{opts[:owner]}:#{opts[:group]} '{}' + || :"
```
This would execute `:`, i.e. the null command, if `find ... -exec chown` fails. Since the null command does nothing but always succeeds, you would see an exit code of 0.

Debug output after fix:
```
DEBUG guest: Searching for cap: rsync_post
DEBUG guest: Checking in: ubuntu
DEBUG guest: Checking in: debian
DEBUG guest: Checking in: linux
DEBUG guest: Found cap: rsync_post in linux
 INFO guest: Execute capability: rsync_post [#<Vagrant::Machine: k8s.local (VagrantPlugins::ProviderVirtualBox::Provider)>, {:type=>"rsync", :rsync__auto=>true, :rsync__verbose=>true, :rsync__exclude=>[".git", ".idea", ".#*"], :create=>true, :guestpath=>"/home/vagrant/workspace", :hostpath=>"/Users/hiep/k8s-dev/workspace", :disabled=>false, :__vagrantfile=>true, :auto=>true, :verbose=>true, :exclude=>[".git", ".idea", ".#*"], :owner=>"vagrant", :group=>"vagrant"}] (ubuntu)
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: find /home/vagrant/workspace -path /home/vagrant/workspace/.git -prune -o -path /home/vagrant/workspace/.idea -prune -o -path /home/vagrant/workspace/.\#\* -prune -o '!' -type l -a '(' ! -user vagrant -or ! -group vagrant ')' -exec chown vagrant:vagrant '{}' + || : (sudo=true)
DEBUG ssh: stderr: mesg: 
DEBUG ssh: stderr: ttyname failed
DEBUG ssh: stderr: : 
DEBUG ssh: stderr: Inappropriate ioctl for device

DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: stderr: find: 
DEBUG ssh: stderr: ‘/home/vagrant/workspace/test.yaml’
DEBUG ssh: stderr: : No such file or directory
DEBUG ssh: stderr: 

DEBUG ssh: Exit status: 0
 INFO rsync-auto: Time spent in rsync: 11.535174 (in seconds)
```

Vagrant rsync-auto will not be stopped, it will recover

### CODE REVIEW

**Comment by chrisroberts** [comment]
Hi, and thank you for this PR. Currently my hesitation with this changeset is that if an error is encountered and the command result is masked (always successful) it can result in a state where some synced files do get their ownership updated.

It looks like the `-ignore_readdir_race` option would address this problem, but I'll still need to do some testing to see if it resolves the issue, and if it's an option that's available within non-gnu find implementations.

**Comment by hieptranquoc** [comment]
@chrisroberts I am very thankful that you have taken care of this issue, which is very important to our project. This error occurs when the host is synchronizing with the guest, while the guest is synchronizing the file to the server. When the file is synchronized to the guest, the file disappears immediately before (or while) the `find..-exec` command occurs. That is very fast, I guess 0.2 0.3s can happen. The example I gave in the issue described the error. I hope you can help and solve this problem!

**Comment by hieptranquoc** [comment]
With this PR, I just make the result is always true. That I tested and it did not happen unexpectedly.

**Comment by hieptranquoc** [comment]
@chrisroberts Thanks for your suggestion. I have tried with `-ignore_readdir_race`, this option can prevent the error occurred with `find`, but when doing `-exec chown` can still occur error.
Result:
```
E, [2018-12-08T03:19:11.149144 #47685] ERROR -- : exception while processing events: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

find /home/vagrant/workspace -path /home/vagrant/workspace/.git -prune -o -path /home/vagrant/workspace/.idea -prune -o -path /home/vagrant/workspace/.\#\* -prune -o  -ignore_readdir_race '!' -type l -a '(' ! -user vagrant -or ! -group vagrant ')' -exec chown vagrant:vagrant '{}' +

Stdout from the command:



Stderr from the command:

chown: cannot access '/home/vagrant/workspace/test.yaml': No such file or directory
 Backtrace:
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/communicators/ssh/communicator.rb:264:in `execute'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/communicators/ssh/communicator.rb:274:in `sudo'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/default_unix_cap.rb:26:in `rsync_post'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/lib/vagrant/capability_host.rb:111:in `call'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/lib/vagrant/capability_host.rb:111:in `capability'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/lib/vagrant/guest.rb:43:in `capability'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/helper.rb:210:in `rsync_single'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/command/rsync_auto.rb:212:in `block (2 levels) in callback'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/command/rsync_auto.rb:201:in `each'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/command/rsync_auto.rb:201:in `block in callback'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/command/rsync_auto.rb:200:in `each'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/command/rsync_auto.rb:200:in `callback'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- /opt/vagrant/embedded/gems/2.2.1/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```
`chown: cannot access '/home/vagrant/workspace/test.yaml': No such file or directory`

**Comment by chrisroberts** [comment]
I believe in this case the option is located in the wrong spot within the command so it is not actually being used. Placing it towards the start should have it evaluated correctly:

```
find /home/vagrant/workspace -ignore_readdir_race -path /home/vagrant/workspace/.git -prune -o -path /home/vagrant/workspace/.idea -prune -o -path /home/vagrant/workspace/.\#\* -prune -o  '!' -type l -a '(' ! -user vagrant -or ! -group vagrant ')' -exec chown vagrant:vagrant '{}' +
```

**Comment by hieptranquoc** [comment]
@chrisroberts Thanks for your advice, I just sent a new PR. Please help me check it. I have tested many and it is absolutely correct expected! Thank you so much 👍

**Comment by chrisroberts** [comment]
@hieptranquoc Thanks for the update. Would you limit the update to only the linux capability (since the `-ignore_readdir_race` option is a GNU only option) and remove the `--quiet` from the `chown` command to keep things consistent.

Thanks!

**Comment by hieptranquoc** [comment]
@chrisroberts After I have tested it thoroughly, this option will not work. The cause is that the `find` command executes quite a long time (~ 4 - 6s), because of a large number of files. Then the `chown` command will be executed, the `-ignore_readdir_race` option can evade the error in the` find` command, but can't avoid the `chown` causing the error. In this case, after I've test carefully, I suppose I will still reserve the opinion: adding `|| :` at the end of the command to exit status returns always 0 (this will not make you worry about `result in a state where some synced files do get their ownership updated.` ). . Please check back to help me that problem. Currently, this error is still occurring with other Unix systems (Darwin, FreeBSD ...) The problem in `find ... -exec` command!

Result:

```
/opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/communicators/ssh/communicator.rb:264:in `execute': The following SSH command responded with a non-zero exit status. (Vagrant::Errors::VagrantError)
Vagrant assumes that this means the command failed!

find /home/vagrant/workspace -ignore_readdir_race -path /home/vagrant/workspace/.git -prune -o -path /home/vagrant/workspace/.idea -prune -o -path /home/vagrant/workspace/.\#\* -prune -o -path /home/vagrant/workspace/node_modules -prune -o -path /home/vagrant/workspace/bower_components -prune -o -path /home/vagrant/workspace/iorad/node/static/downloadtutorials/html -prune -o -path /home/vagrant/workspace/iorad/.tmp -prune -o -path /home/vagrant/workspace/iorad/app/scripts/base/templates/dist -prune -o -path /home/vagrant/workspace/iorad/app/scripts/editor/templates/dist -prune -o -path /home/vagrant/workspace/iorad/app/scripts/editor/workers/dist -prune -o -path /home/vagrant/workspace/iorad/app/scripts/player/templates/dist -prune -o -path /home/vagrant/workspace/iorad/app/scripts/player/workers/dist -prune -o -path /home/vagrant/workspace/iorad/node/static/_dist -prune -o -path /home/vagrant/workspace/iorad/node/static/dist -prune -o -path /home/vagrant/workspace/iorad/node/static/assets/css -prune -o -path /home/vagrant/workspace/iorad/node/static/webstart -prune -o -path /home/vagrant/workspace/iorad/node/static/data -prune -o -path /home/vagrant/workspace/iorad/node/static/assets/avatars -prune -o -path /home/vagrant/workspace/iorad/node/webpack-assets.json -prune -o -path /home/vagrant/workspace/target -prune -o -path /home/vagrant/workspace/.backup-info -prune -o -path /home/vagrant/workspace/iorad/helm-charts -prune -o -path /home/vagrant/workspace/iorad/scripts -prune -o -path /home/vagrant/workspace/iorad/.cache -prune -o -path /home/vagrant/workspace/build -prune -o -path /home/vagrant/workspace/dist -prune -o '!' -type l -a '(' ! -user vagrant -or ! -group vagrant ')' -exec chown vagrant:vagrant '{}' +

Stdout from the command:



Stderr from the command:

chown: cannot access '/home/vagrant/workspace/test.yaml': No such file or directory
	from /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/communicators/ssh/communicator.rb:274:in `sudo'
	from /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/default_unix_cap.rb:26:in `rsync_post'
	from /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/lib/vagrant/capability_host.rb:111:in `call'
	from /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/lib/vagrant/capability_host.rb:111:in `capability'
	from /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/lib/vagrant/guest.rb:43:in `capability'
	from /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/plugins/synced_folders/rsync/helper.rb:210:in `rsync_single'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:149:in `do_rsync'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:142:in `block (2 levels) in callback'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:140:in `each'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:140:in `block in callback'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:139:in `each'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:139:in `callback'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/listen/listenosx.rb:47:in `call'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/listen/listenosx.rb:47:in `block in run'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/listen/listenosx.rb:31:in `loop'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/listen/listenosx.rb:31:in `run'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:94:in `execute'
	from /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/lib/vagrant/cli.rb:58:in `execute'
	from /opt/vagrant/embedded/gems/2.2.1/gems/vagrant-2.2.1/lib/vagrant/environment.rb:291:in `cli'
	from /Users/hiep/.vagrant.d/gems/2.4.4/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/action/startup_rsync.rb:40:in `block in call'
```

I think the only way to add `|| :`  to the end of the command is to stop this problem without causing an error

**Comment by chrisroberts** [comment]
@hieptranquoc I don't believe that forcing a successful result is the correct solution to the problem, unfortunately. If the command is failing, we want that to be surfaced and reported. If the error is not surfaced to the user, then the result will be unexpected behavior with a lack of any obvious cause. At this point I think there are two options:

1. Update your configuration to not apply the chown using the [rsync__chown](https://www.vagrantup.com/docs/synced-folders/rsync.html#rsync__chown) option
2. Allow the command to be retried be `N` times before failure (making the count configurable and defaulted to 1 to retain existing behavior)

The latter would be the long term solution to this issue. If it's something you're interested in implementing, that would be great. Otherwise, we will add it to the backlog and look at adding the feature when we have time.

**Comment by hieptranquoc** [comment]
@chrisroberts I understand that you do not want to force the exit status to 0. I am very interested in this error because it has a great influence on our problem, so I will try to fix the most suitable for your expected.
I have updated my PR, I hope you will agree with this new solution.
I found that Vagrant did not have that error, so I created a new error class when rsync `find .. chown` command encountered that error, will recover and report error. You give me feedback! Thank you so much.
this is example log after fixing:
```
==> k8s.local: Rsyncing folder: /Users/hiep/k8s-dev/workspace/ => /home/vagrant/workspace
==> k8s.local:   - Exclude: [".vagrant/", ".git", ".idea", ".#*"]
==> k8s.local: There was an error while executing find and chown command, when file missing.
==> k8s.local: This may not be critical since rsync chown command sometimes fails, but if this message
==> k8s.local: repeats, then please fix the issue.
==> k8s.local: Rsyncing folder: /Users/hiep/k8s-dev/workspace/ => /home/vagrant/workspace
==> k8s.local:   - Exclude: [".vagrant/", ".git", ".idea", ".#*"]
==> k8s.local: Rsyncing folder: /Users/hiep/k8s-dev/workspace/ => /home/vagrant/workspace
==> k8s.local:   - Exclude: [".vagrant/", ".git", ".idea", ".#*"]
```

**Comment by chrisroberts** [comment]
@hieptranquoc I think that this is on the right track. I have updated things a little bit to make it more generic and add some test coverage. The branch is here:

https://github.com/chrisroberts/vagrant/tree/pr-10461

Would you give that a test and confirm that it still resolves your issue. If so I'll add the commits in and we can get that merged. Thanks!

**Comment by chrisroberts** [comment]
Great, thanks for confirming! I have created a new PR (#10515) which includes your initial changes (minus the merge commits) and has the updates from my branch added on top. I'm going to close this PR up in favor of the new updated PR. Thanks for reporting the issue and working towards this solution!

Cheers!

**Pull request closed without merging**
