### PR TITLE
Add void linux host support

### PR DESCRIPTION
**Pull request by Aloz1**
Currently, NFS does not work correctly on void linux. This PR adds a new Void Linux host to fix this. An issue has been opened here: #10011

### CODE REVIEW

**Comment by Aloz1** [comment]
Hm, nfs_start_command is wrong. Will need to fix it tonight when I get home. (Should probably be something along the lines of "ln -s /etc/sv/nfs-server /var/services/."

**Comment by Aloz1** [comment]
Hm, need to investigate some more. As it stands, I'm unable to get NFSv3 working, and NFSv4 only works if the export has has no_root_squash. This is probably a void issue, but suggestions would be appreciated.

**Comment by Aloz1** [comment]
NFSv3 works fine now, void requires root access to check service status, hence vagrant was attempting to start up nfs-server rather than 'export -ar'.

Additionally, it appears that NFSv4 works fine. Seems I had the same problem as #8279.

**Comment by Aloz1** [comment]
This PR is ready for review...

**Comment by GoingFast** [comment]
@briancain @chrisroberts going to take another 3 months? the fix is up so whats the problem? nfs is unusable for void users

**Comment by Aloz1** [comment]
Looks like it's been tagged as needing tests (I unfortunately didn't get a notification when the label was added). I'm not very experienced with ruby, let alone unit testing in ruby, so might take me a little bit to figure things out.

I'll investigate and see if I can come up with something over the next couple of days.

**Comment by chrisroberts** [comment]
@Aloz1 I've pushed an update to this PR. If you sign off on the CLA I'll get this merged and included with the next release.

**Comment by Aloz1** [comment]
@chrisroberts thanks for helping out with getting this over the line, its much appreciated!!!

**Pull request merged**
