### PR TITLE
Fix ansible_install for several guest caps

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, several guests were not updated to support the additional parameter `pip_install_cmd`. This commit includes that param, even if it goes unused in the guests. Without this param, Vagrant would crash expecting 4 params on the guest capability, rather than the passed in 5.

This pull request also brings in the PR https://github.com/hashicorp/vagrant/pull/11061, which updates the package used on FreeBSD for installing ansible.

### CODE REVIEW

**Comment by gildegoma** [comment]
@briancain could you please maybe consider bringing changes in #11227 (instead of 02b1ed65ec0824e5fbac5b853c63c1d77d7e412e).

**Comment by briancain** [comment]
@gildegoma - hmm, only if they are ready to be merged. It seems like that pull request is still being worked on? While this change doesn't fully support the pip install method, it will at least prevent people from seeing a stacktrace where Vagrant passed in the wrong number of parameters to the ansible_install capability.

**Comment by gildegoma** [comment]
@briancain sure, this is important to get this fixed anyways in the next release. That said, you can review (and merge) #11227 as it is. I'll add more unit tests in a next step (not that urgent, as you can see in #6633 for the overdue records ;-)

**Comment by briancain** [comment]
@gildegoma - oooh ok, sounds good! I'll do that today, and rebase this PR and fix up any merge conflicts. Then maybe if you could add a couple of issue enhancements around the remaining work so it doesn't get lost, that would be great! :smile: Thanks again :tada:

**Comment by briancain** [comment]
Sorry for the run-around everyone. I've moved these changes into a _new_ PR, https://github.com/hashicorp/vagrant/pull/11265. This includes the work described above, along with the original patch to fixup installing ansible on FreeBSD.

**Pull request closed without merging**
