### PR TITLE
Fix Ruby 2.4+ compatibility.

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by swills** [comment]
What's the status of this?

**Comment by swills** [comment]
Never mind, answered my question. Seems this still fails some tests. See [the travis log](https://travis-ci.org/swills/vagrant/jobs/250037697) for details.

**Comment by briancain** [comment]
Hi all - I've rebased this PR, and included a few new commits to get this merged into Vagrant. Check it out here: #9102

Going to close this now. thanks!!

**Comment by voxik** [comment]
@briancain 👍 thx

**Pull request closed without merging**
