### PR TITLE
Homepage: mention that Vagrant is free software

### PR DESCRIPTION
**Pull request by hexagonrecursion**
As far as I can tell Vagrant is free software. This is a big deal for some people (like me). This is a big enough feature to mention it on your homepage.

Note: I could not find a detailed list of components/plugins and their licenses in your documentation. Is all of Vagrant MIT-licensed? Are some parts released under a different license?

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
@alexcarpenter ping?

**Comment by hexagonrecursion** [comment]
@dstaley ping

**Comment by dstaley** [comment]
Hi @hexagonrecursion, sorry it's taken us a bit to respond! Thank you for your pull request. Since the homepage is something our marketing team has purview over, I've passed this along to them. Open source software is at the heart of HashiCorp, so I appreciate you wanting to call that out! :)

**Comment by hexagonrecursion** [comment]
closing

image

**Pull request closed without merging**
