### PR TITLE
Hyper v networks

### PR DESCRIPTION
**Pull request by wiltaylor**
Added multiple nic support for Hyper V as per #8849.

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
If possible, let's make sure the Hyper-V commands are fully qualified per discussion in #8849 prior to merge. Thanks for reaching out!

**Comment by wiltaylor** [comment]
Yep will do, had a few things on at work so haven't had a chance to update it yet :).

**Comment by bbrala** [comment]
@wiltaylor got time to rebase sometime soon? :)

**Comment by wiltaylor** [comment]
@bbrala sorry this has been sitting on my todo list for ages. I will try and do it sometime this week.

**Comment by briancain** [comment]
Hey there! Due to the rebase that this pull request needs (which is partially our fault for not addressing this sooner!), and the fact that there have been quite a few updates to the Hyper-V provider since this was last addressed, I'm going to go ahead and close this PR. I've placed the original issue in an up coming milestone so that our team can plan and properly address this feature for the Hyper-V provider. Thanks again for doing all of this work initially to get this going, and apologies that we did not look at it and provide proper feedback sooner.

**Pull request closed without merging**
