### PR TITLE
Ensure Hyper-V cmdlets are fully qualified

### LINKED ISSUE #8862: Hyper-V Provider Fails when PowerCLI is Installed
### Vagrant version
`1.9.7`

### Host operating system
Windows `10.0.14393`

### Guest operating system
CentOS 7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "hyperv"
  config.vm.network "public_network", bridge: "Guest"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true
    h.differencing_disk = true
  end
end
```

### Debug output
The full [debug output can be found in this gist](https://gist.github.com/michaeltlombardi/439dea9a254093799b811ea60658818c), but the relevant part is below:

```
DEBUG subprocess: stderr: Get-VM : 8/8/2017 11:28:54 AM	Get-VM		You are not currently connected to any servers. Please connect first using a 
Connect cmdlet.	
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.9.7\plugins\providers\hyperv\scripts\import_vm_xml.ps1:40 char:5
+     Get-VM | ForEach-Object -Process {
+     ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-VM], ViServerConnectionException
    + FullyQualifiedErrorId : Core_BaseCmdlet_NotConnectedError,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetVM
```

Notice in this case that the cmdlet that failed is a VMware cmdlet, not from the Hyper-V module.

### Expected behavior
The VM should have launched as expected.

### Actual behavior
A failure occurred because the command `Get-VM` is ambiguous when both the PowerCLI and Hyper-V modules are available on a system.

### Steps to reproduce
1. Ensure Hyper-V is installed
2. Install the PowerCLI module (`Install-Module PowerCLI`)
3. Launch a vagrant box using the Hyper-V provider.

### Possible Fix
Fully qualify the Hyper-V commands in the script files to disambiguate the calls. I can submit a PR for this. for example instead of:

```powershell
Get-VM | ForEach-Object -Process {
    ...
}
```

We would include the Module name prior to the the function or cmdlet call:

```powershell
Hyper-V\Get-VM | ForEach-Object -Process {
    ...
}
```

### PR DESCRIPTION
**Pull request by michaeltlombardi**
+ This disambuguates calls to the Hyper-V functions for the Hyper-V provider.
The ambiguity of some commands - such as `Get-VM` - causes the Hyper-V provider
to fail on systems where VMware PowerCLI is installed. This change ensures that
all calls to Hyper-V specific cmdlets or functions are prepended by `Hyper-V\`.
This ensures the correct cmdlet calls are being made.
+ Resolves  #8862.

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
Weird that the build failed on grabbing rspec dependencies.

**Comment by briancain** [comment]
@michaeltlombardi - This is because are are in the middle of upgrading vagrants rspec version. Once #8850 has been merged, travis should be able to pass. Thanks!

**Comment by michaeltlombardi** [comment]
That makes sense!

**Comment by michaeltlombardi** [comment]
I missed the addition of the pr/needs-rebase tag - I can rebase if the rspec stuff is cleared up by now?

**Comment by briancain** [comment]
@michaeltlombardi - Yep, that's been merged. You should be ok to rebase.

**Comment by bbrala** [comment]
@michaeltlombardi could you find time to rebase this?

**Comment by michaeltlombardi** [comment]
@bbrala Sorry! Fell off my radar for a bit again. Done, while I was thinking about it and drinking my breakfast coffee. :)

**Comment by michaeltlombardi** [comment]
Looks like travis failed due a timeout; I don't have user rights to rekick the job though.

**Comment by bbrala** [comment]
Cool thanks! 

Perhaps this can be merged then coming release @chrisroberts ? :)

**Comment by briancain** [comment]
I rekicked the travis job @michaeltlombardi

**Comment by michaeltlombardi** [comment]
Looks like that did it, @briancain, tests are all passing! 🎉

**Comment by michaeltlombardi** [comment]
Is there anything left I need to do to get this merged?

**Comment by briancain** [comment]
Thanks for your contribution @michaeltlombardi !

**Pull request merged**
