### PR TITLE
Add support for the Haiku operating system

### PR DESCRIPTION
**Pull request by kallisti5**
Adds support for the Haiku operating system.

See enhancement #7803

### CODE REVIEW

**Comment by avongluck-r1soft** [comment]
I've updated the Haiku box for testing purposes.  The default 'user' user has been renamed 'vagrant' to make getting it running easier.

```vagrant init haikuos/x86_64; vagrant up --provider virtualbox```

**Comment by kallisti5** [comment]
Any chance of this getting pulled?  We're way past 1.9.0 :-|

**Comment by kallisti5** [comment]
Guys/Ladies?

**Comment by kallisti5** [comment]
thanks for reviewing :-)

**Pull request merged**
