### PR TITLE
Fix the included Vagrantfile for running rspec tests

### PR DESCRIPTION
**Pull request by timvisher**
In attempting to get a development environment set up to run the rspec
tests for a forthcoming PR I noticed that the Vagrantfile doesn't appear
to actually set up a functioning environment. I'm not sure when this
changed or how it's been missed but I figured I'd contribute a patch to
fix it up for my benefit and others.

In summary:

1. RVM no longer appears to be installed and configured the way the
   current provisioning script expects it be. Namely it requires users to
   be added to the `rvm` group rather than the `sudo` group and also
   requires a log out and then back in to finish setting up. In light of
   that I broke apart the provisioning into two separate shell scripts to
   get that 'log out and back in' behavior.
2. While I was there I tried to 'clean up' the script's logic, making it
   idempotent, using `sudo -u vagrant -i` rather than the `su`
   incantation, removing apparentyl unnecessary dependencies like
   `build-essential` and the GPG key, etc. I suspect there's some
   significant unnecessary complexity in the ruby version extraction but
   that could be tacked on later. This change is already big enough.
   
What do you think? I'm happy to cleanup the commits if there's interest in
the patch.

---

```
$ vagrant -v; VBoxManage -v
Vagrant 2.2.14
6.1.18r142142
```

Pre Change:

```
$ time {
    vagrant destroy -f &&
    vagrant up &&
    vagrant ssh-config |
      tee default.conf &&
    ssh -F default.conf default $'
      bash -lc \'
        hostname;
        date;
        cd /vagrant &&
          bundle exec rake; hostname
      \'
    '
  }
…
(Reading database ... 45709 files and directories currently installed.)
    default: Preparing to unpack .../git_1%3a2.17.1-1ubuntu0.8_amd64.deb ...
    default: Unpacking git (1:2.17.1-1ubuntu0.8) over (1:2.17.1-1ubuntu0.4) ...
    default: Setting up git (1:2.17.1-1ubuntu0.8) ...
    default: Ruby ruby-2.6.6 is not installed.
    default: -su: bundle: command not found
…

vagrant
Mon Apr 12 15:42:40 UTC 2021
bash: line 4: bundle: command not found
vagrant

real    3m7.343s
user    0m13.897s
sys     0m4.263s
```

Post Change:

```
$ time {
    vagrant destroy -f &&
    vagrant up &&
    vagrant ssh-config |
      tee default.conf &&
    ssh -F default.conf default $'
      bash -lc \'
        hostname;
        date;
        cd /vagrant &&
          bundle exec rake; hostname
      \'
    '
  }
…
Finished in 19 minutes 2 seconds (files took 3.09 seconds to load)
4674 examples, 0 failures, 3 pending

vagrant

real    26m21.810s
user    0m13.517s
sys     0m4.281s
```

### CODE REVIEW

**Comment by timvisher** [comment]
Ping on this. :)

**Comment by timvisher** [comment]
Ping on this. :)

**Comment by timvisher** [comment]
Last ping on this then I'll guess I'll close it assuming we're not interested.

**Review by chrisroberts — APPROVED** [review]
Sorry, for the delay on getting to this. Thank you!

**Comment by chrisroberts** [comment]
@timvisher if you would squash down the `wip` commits before we merge, that would be super :slightly_smiling_face:

**Comment by timvisher** [comment]
Should be good to go. :)

**Review by soapy1 — APPROVED** [review]

**Pull request merged**
