### PR TITLE
Fix typo in upload CLI docs

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
In many CLA's there's an exception for such trivial changes but I don't see it when I quickly read through it. Is there such a thing? IANAL, but I doubt I could claim copyright on this. I'd like to avoid signing it so I don't have to check the CLA with legal.

**Comment by briancain** [comment]
Hey there @ekohl - Sorry, as far as I know there aren't any exceptions for any kind of changes, however small they may be. It's alright if you can't get it signed, I can open a new pull request to fix the typo if you can't get the CLA approved. Let me know what you want to do, thanks!

**Comment by ekohl** [comment]
Please do. I'd rather not for something so trivial. Consider this a bug report then :)

**Comment by briancain** [comment]
Thanks @ekohl !

**Pull request closed without merging**
