### PR TITLE
Feature request: attach secondary disk on Hyper-V

### PR DESCRIPTION
**Pull request by JohnEricson**
This is a pull request to solve reported feature request issue at https://github.com/hashicorp/vagrant/issues/8648.

The original code for this was created in issue https://github.com/hashicorp/vagrant/pull/6321. Part of it has already been merged but this part is left. I've implemented what @mwrock wanted:

* Improved configuration format. No more nested arrays. More future proof.
* Now size of disks are specified in MB instead of GB.

I couldn't implement the configuration format exactly. Instead I came up with this format which I believe is very similar:

```ruby
hv.controller type: :scsi, disks: [ "d2", 10 * 1024 ]
```

This creates a SCSI controller and a new disk that is 10 GB big.

IDE and attaching already existing disks are not implemented but configuration format for this is already implemented like this:

```ruby
# Throws TODO-error because IDE-support is not implemented yet.
hv.controller type: :ide, disks: [ "d1", 20 * 2048 ]

# Throws TODO-error when file exists because this isn't implemented yet.
hv.controller type: :scsi, disks: [ "c:/disk.vhdx" ]
```

I've also added documentation for the new feature. Looking forward to seeing this get merged into Master.

### CODE REVIEW

**Comment by almightyfoon** [comment]
Whats the status on this PR? It would be very helpful to have.

**Comment by JohnEricson** [comment]
Hi @almightyfoon! I'm waiting on a developer to make an approved review of it. I'm very dedicated to get this included as well as I also rely on this feature, so I would really appreciate it if @chrisroberts or anyone else can make it happen.

**Comment by JohnEricson** [comment]
I hope everything should be done for merging now. Please, let me know if you need me to done anything more.

**Comment by mloskot** [comment]
Can we have this merged?

**Comment by Yivan** [comment]
@JohnEricson Very very nice new feature !!
We managed it through custom scripts until now. Main purpose was having a dedicated disk for storing the code, so recreating the VM could be simply done without to lost the code.

Just, when doing a `vagrant destroy` is this secondary disk keeped or deleted (like the main one).
Main purpose of having this secondary disk is to preserve it through recreation of the VM.
If not, may a parameter be added ?
I think it is very valuable for usefullness od this new feature!

Thansk a lot.

**Comment by JohnEricson** [comment]
@Yivan 
> Just, when doing a `vagrant destroy` is this secondary disk keeped or deleted (like the main one) ?

I hope this feature can help you too. Always better if it can be solved by Vagrant out of the box. Now the secondary disk is deleted just like the main one.

But I've implemented support in the config to specify a current disk like this:

```ruby
# Throws TODO-error when file exists because this isn't implemented yet.
hv.controller type: :scsi, disks: [ "c:/disk.vhdx" ]
```

Although the actual logic to attach the disk isn't implemented yet. But perhaps the default behavior when an already existing disk is attached like that could be to preserve it on mount, or specify that behavior using an extra option.

**Comment by Yivan** [comment]
@JohnEricson Thanks for your return on this. Great feature yes!

Having a parameter to prevent destorying disk during `vagrant destroy` would be really great. If this parameter is activated, so the disk should be unmounted before destroying the VM. This is the way we handle it manually actually (with triggers).

Thanks!

**Comment by briancain** [comment]
Hey there everyone! I'm going to go ahead and close this issue, as I have just made a pull request that takes advantage of the recent generic disk config options in Vagrant. You can find that PR here: #11541 It offers a lot of extra goodies such as resizing disks (similar to the VirtualBox implementation). Thanks!

**Pull request closed without merging**
