### PR TITLE
remove all space from checksums

### PR DESCRIPTION
**Pull request by cjmartian**
This is related to #12113 
I'm not sure if we would prefer to use `.strip()` to remove only leading and trailing space instead of removing all of it the way I do in this PR.

### CODE REVIEW

**Comment by chrisroberts** [comment]
Hi @cjmartian and thanks for this PR! I think that using the `#strip` method would be best here (even though checksums shouldn't include space characters anywhere). We only want to ensure any leading/trailing space characters are removed. Adding a test case for this would be appreciated as well. 

Please note that before we can merge we'll need the CLA signed too. Thanks so much!

**Review by chrisroberts — CHANGES_REQUESTED** [review]
As noted in comment, `#strip` usage and test coverage :slightly_smiling_face:

**Comment by cjmartian** [comment]
Hey @chrisroberts, 

Thank you for the feedback, this is my first time writing ruby so the feedback is more than welcome! I've made changes to use strip() instead. I'm writing a test for this now, I'd like to get feedback on that once I push.

Thank you again for looking at this.

**Review by soapy1 — APPROVED** [review]
Thanks!

**Pull request merged**
