### PR TITLE
docs: fix typo and clarify sentence

### PR DESCRIPTION
**Pull request by siiky**

### CODE REVIEW

**Review by Gauravms2143 — DISMISSED** [review]
LGTM

**Comment by ashleemboyer** [comment]
Hi @siiky! I've just merged in https://github.com/hashicorp/vagrant/pull/13048, which modified 120 MDX files and added a new workflow that would be good to have run on this PR. Since this is from a fork, I'm not sure I have permissions to rebase on `main` for you, so I wanted to send this quick message to let you know to update with `main`. Thanks!

**Comment by siiky** [comment]
I'll try to rebase it later today, no problem.

**Comment by siiky** [comment]
@ashleemboyer Took me a littler longer but here it is.

**Comment by soapy1** [comment]
Thanks for trying to make the Vagrant docs better! We appreciate the time you took to look at our documentation and submit this PR. I think these changes can be expanded on a little more. I’ve done that in this change https://github.com/hashicorp/vagrant/pull/13085. So, I’m going to go ahead and close this PR.

**Comment by siiky** [comment]
Well, it's your project after all, so if you think so...

**Pull request closed without merging**
