### PR TITLE
SSH communicator - Reset retries counter, sleep between connection attempts

### PR DESCRIPTION
**Pull request by avoidik**
Relevant issue - #12270

Rework of https://github.com/hashicorp/vagrant/pull/12272

### CODE REVIEW

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by avoidik** [comment]
Hello over there,

There's still no gap between connection attempts, and SSH exceptions aren't considered as retryable in the latest version, but of course it's up to you to decide is this a bug or feature.

Cheers.

**Comment by soapy1** [comment]
Hey there,

>There's still no gap between connection attempts

Yup, that issue is open at https://github.com/hashicorp/vagrant/issues/10776. I think it would be nice if the solution had user configurable retry delay, similar to the [winrm plugin](https://developer.hashicorp.com/vagrant/docs/vagrantfile/winrm_settings#config-winrm-retry_delay). This is addressed in an existing PR https://github.com/hashicorp/vagrant/pull/13047. 

Thanks for the contribution!

**Comment by avoidik** [comment]
Hey @soapy1 

Worth noting that in the current implementation there is no retries at all due to this line, which effectively limits retries to 1.

https://github.com/hashicorp/vagrant/blob/main/plugins/communicators/ssh/communicator.rb#L87

Could you please finally decide in which PR you would like to see this fix to be applied without removing my comments? Thank you.

**Comment by soapy1** [comment]
> Worth noting that in the current implementation there is no retries at all due to this line, which effectively limits retries to 1.

yup, I see you also noted this as a [comment](https://github.com/hashicorp/vagrant/pull/13047) on the above mentioned PR. So, I think it's appropriate to resolve it in PR#13047. Thanks for your contribution!

**Pull request closed without merging**
