### PR TITLE
Update smb.html.md

### PR DESCRIPTION
**Pull request by TonyApuzzo**
Document a PowerShell one-liner to clean up all the existing SMB shares.

### CODE REVIEW

**Comment by briancain** [comment]
Hey there @TonyApuzzo - Were you encountering Vagrant leaving these shares behind when using smb? If so, that's likely a vagrant bug and we'd be happier to fix that instead of documenting this fix. Thanks!

**Comment by TonyApuzzo** [comment]
Hi, yes, Vagrant does have that limitation, see the paragraph above my diff in the file:

> The primary limitation of SMB synced folders at the moment is that they are never pruned or cleaned up. Once the folder share is defined, Vagrant never removes it. To clean up SMB synced folder shares, periodically run net share in a command prompt, find the shares you do not want, then run net share NAME /delete for each, where NAME is the name of the share.

**Comment by TonyApuzzo** [comment]
(I always seem to hit the "close" button accidentally...)

**Comment by briancain** [comment]
Right, if that's the case I would rather fix that in Vagrant instead of documenting a work around. I recommend opening an issue with a Vagrantfile and we can go ahead and triage it and get it fixed. Thanks!

**Pull request closed without merging**
