### PR TITLE
WIP: Install docker-ce instead of docker for docker provisioner

### PR DESCRIPTION
**Pull request by lioramilbaum**

### CODE REVIEW

**Comment by lioramilbaum** [comment]
@briancain Thank you for taking the time to review my PR. Can you share more information on how the user can choose which docker to install?

**Comment by lioramilbaum** [comment]
@briancain I am hitting an error when dnf is used:

➜ vagrant git:(docker-ce) ✗ bundle exec vagrant up        

You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'fedora/31-cloud-base'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'fedora/31-cloud-base' version '31.20191023.0' is up to date...
==> default: Setting the name of the VM: training_default_1576907769982_9819
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Rsyncing folder: /Users/liora/src/github.com/lioramilbaum/training/ => /vagrant
==> default: Running provisioner: docker...
    default: Installing Docker onto machine...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

dnf -y install docker-ce

Stdout from the command:

Docker CE Stable - x86_64                        19 kB/s | 6.6 kB     00:00    
Fedora Modular 31 - x86_64                      4.4 MB/s | 5.2 MB     00:01    
Fedora Modular 31 - x86_64 - Updates            2.1 MB/s | 3.9 MB     00:01    
Fedora 31 - x86_64 - Updates                    4.4 MB/s |  15 MB     00:03    
Fedora 31 - x86_64                               11 MB/s |  71 MB     00:06    


Stderr from the command:

bash: line 4:  2453 Killed                  dnf -y install docker-ce

➜ vagrant git:(docker-ce) ✗

**Comment by briancain** [comment]
Hey there @lioramilbaum - I haven't been able to reproduce that at all. Perhaps dnf just timed out and the process was killed?

**Comment by lioramilbaum** [comment]
@briancain I have filed a different issue to track this error - #11277

**Comment by briancain** [comment]
Hey there, I'm going to go ahead and close this, as I believe it was covered initially via this PR: https://github.com/hashicorp/vagrant/pull/11462 Thanks!

**Pull request closed without merging**
