### PR TITLE
Add support for VirtualBox 7.1

### PR DESCRIPTION
**Pull request by chrisroberts**
Adds support for the 7.1.x versions of VirtualBox to the builtin provider plugin.

### CODE REVIEW

**Comment by justdan96** [comment]
This PR appears to be missing this change: https://github.com/hashicorp/vagrant/blob/507d5983becdab30d443bb25800f607bcabfc283/plugins/providers/virtualbox/driver/meta.rb#L72

**Comment by hswong3i** [comment]
Some more miss:
```
diff --git a/website/content/docs/providers/virtualbox/index.mdx b/website/content/docs/providers/virtualbox/index.mdx
index 6c685971f..96f47151c 100644
--- a/website/content/docs/providers/virtualbox/index.mdx
+++ b/website/content/docs/providers/virtualbox/index.mdx
@@ -12,7 +12,7 @@ Vagrant comes with support out of the box for [VirtualBox](https://www.virtualbo
 a free, cross-platform consumer virtualization product.
 
 The VirtualBox provider is compatible with VirtualBox versions 4.0.x, 4.1.x,
-4.2.x, 4.3.x, 5.0.x, 5.1.x, 5.2.x, 6.0.x, 6.1.x and 7.0.x. Other versions are unsupported and the provider
+4.2.x, 4.3.x, 5.0.x, 5.1.x, 5.2.x, 6.0.x, 6.1.x, 7.0.x and 7.1.x. Other versions are unsupported and the provider
 will display an error message. Please note that beta and pre-release versions
 of VirtualBox are not supported and may not be well-behaved.
```

**Comment by hswong3i** [comment]
> This PR appears to be missing this change:
> 
> https://github.com/hashicorp/vagrant/blob/507d5983becdab30d443bb25800f607bcabfc283/plugins/providers/virtualbox/driver/meta.rb#L72
> 
> Without this Vagrant will continue to see VirtualBox 7.1 as unsupported.

Specifically patch could be:
```diff
diff --git a/plugins/providers/virtualbox/driver/meta.rb b/plugins/providers/virtualbox/driver/meta.rb
index 4b1878bde..63af500c6 100644
--- a/plugins/providers/virtualbox/driver/meta.rb
+++ b/plugins/providers/virtualbox/driver/meta.rb
@@ -69,7 +69,6 @@ module VagrantPlugins
             "6.0" => Version_6_0,
             "6.1" => Version_6_1,
             "7.0" => Version_7_0,
+            "7.1" => Version_7_1,
           }
 
           if @@version.start_with?("4.2.14")
```

**Comment by Insua** [comment]
please release new version as quickly as possible

**Review by allisonlarson — APPROVED** [review]

**Comment by tesla59** [comment]
it has been a while since a new vagrant release. when can we expect this to be released?

**Comment by chrisroberts** [comment]
I'm actively working through the last of the open items I want addressed in this release, so it will be soon. In the meantime, this changeset will be included in the nightly builds (and is included in this [dev build](https://github.com/hashicorp/vagrant/releases/tag/2.4.2.dev%2B000314-a82b64d1) that I kicked off earlier).

**Comment by daxiangroup** [comment]
Hey @chrisroberts, curious on a ballpark for "soon".  I'm not trying to poke the bear here, or tie you to an actual date, just wondering if soon is days or weeks? (I understand there are nightlies...)

**Comment by chrisroberts** [comment]
@daxiangroup my target is no later than end of day tomorrow.

**Comment by daxiangroup** [comment]
> @daxiangroup my target is no later than end of day tomorrow.

hero!

**Pull request merged**
