### PR TITLE
#9298: Compute a correct path to the current WSL instance

### PR DESCRIPTION
**Pull request by BR0kEN-**
https://github.com/hashicorp/vagrant/issues/9298

### CODE REVIEW

**Comment by BR0kEN-** [comment]
Just checked this on SUSE and it turned out that some tweaks were required.

The previous script for obtaining Linux distro:

```python
python -c "import platform;print(platform.linux_distribution()[0]"
```

And the new one:

```python
python -c "import platform;print(platform.linux_distribution()[0].split(' ')[0])"
```

wsl-multi

**Comment by BR0kEN-** [comment]
The PR brings not an elegant way of solving the problem but, apparently, it works.

Checked on three WSL distros: SUSE Server (the new method `linux_distro` will return `SUSE`), openSUSE (`linux_distro` -> `openSUSE`) and Ubuntu (`linux_distro` -> `Ubuntu`).

Of course, as said in the https://github.com/Microsoft/WSL/issues/2578#issuecomment-353900973, there could be a custom distro that won't be handled in that way, but for now this approach is multi-environment at least.

**Comment by BR0kEN-** [comment]
The implementation has been changed based on investigation I've described in https://github.com/Microsoft/WSL/issues/2578#issuecomment-354010141.

**Comment by chrisroberts** [comment]
@BR0kEN- Thanks for this PR and the underlying investigation to create it! Once I have validated the functionality on a few versions of win10, I'll get it approved and merged.

**Comment by temoor-gilmutdinov** [comment]
Hi there, checked it on Win10, version 10.0.16299.192. Works well.

**Comment by BR0kEN-** [comment]
My tests, unfortunately, were on the same build of Win10.

**Comment by chrisroberts** [comment]
@BR0kEN- Hi and thanks again for all the hard work you put into this PR. It is greatly appreciated. I'm going to close this PR in favor of #9525 which adds in support for the original lxrun generated WSL instance types and adds a bit of spec coverage. It is built directly on top of your changes, so even though this PR is being closed, your changes will still be getting merged.

Thanks again!

**Pull request closed without merging**
