### PR TITLE
Add Virtualbox 7.0 support

### LINKED ISSUE #12947: Vagrant not working with Virtualbox 7.0
<!--
Now with Virtualbox 7.0 released [ https://www.virtualbox.org/ ], Vagrant 2.3.1 does *not* recognize 7.0 and does not work. [Using Windows 11 Pro]
It says

```
C:\b>vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```

I tried overriding it to run but it didn't work
```
C:\b>vagrant up --provider=virtualbox
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0, 6.1

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
```
### Expected behavior

It should run as normal

#### Vagrant version

```
Vargrant 2.3.1
```
#### Host operating system

Windows 11 Pro 22H2

#### Guest operating system

Rocky Linux 9

#### Steps to reproduce

1. Upgrade from Virtualbox 6.xx to Virtualbox 7.xx
2. Run vagrant up

### PR DESCRIPTION
**Pull request by T2L**
Just incorporating awesome job by @scoter-oracle. See https://blogs.oracle.com/scoter/post/getting-vagrant-23-working-with-oracle-vm-virtualbox-70-beta

Fixes #12947

### CODE REVIEW

**Review by identifysun — APPROVED** [review]

**Review by identifysun — APPROVED** [review]

**Comment by T2L** [comment]
So, technically I can't sign CLA ... as this code is from article by @scoter-oracle, I do not own it ... I guess we will need their approval

With this patch, vagrant is able to work with Virtualbox 7.0.0, but it hangs (at least on x86 MacOS)

**Comment by leet4tari** [comment]
As noted in the article @scoter-oracle, port redirection does not work. Still needs work.

**Comment by scoter-oracle** [comment]
Standard port redirection (port 22 on Linux) just works. It does not work if you add more than that.

**Comment by scoter-oracle** [comment]
I'm investigating internally with the VBox team on the port-redirection issue; that said, this code has to be pushed in any case. If an approval is required from my side to see the code merged, I approve!

**Comment by maifujalam** [comment]
Please tell when vagrant will be available for Virtualbox7.0?

**Comment by identifysun** [comment]
@scoter-oracle  I guess you're not just approve, you need to signed the CLA. 

@hashicorp-cla will merge it.

**Comment by scoter-oracle** [comment]
CLA signed.

**Comment by scoter-oracle** [comment]
Further information: related to the issue faced with custom "Port Forwarded" there's an issue on VirtualBox.
I've opened an internal bug to the VirtualBox engineering team on this; this is the finding:

noted that "vboxmanage showvminfo --machinereadable" does not show (anymore) Forwarded Ports, while it was on 6.1.

Example - more forwarded ports configured.
===
output on 6.1:

Forwarding(0)="ssh,tcp,127.0.0.1,222222"
Forwarding(1)="tcp8080,tcp8080,,80"
====
output on 7.0 does not show none of them

If you have only one forwarded-port rule configured the same is correctly shown.
If you have more than one, on 7.0 following issue happens:

- with "machinereadable" option, non of them is showed
- without "machinereadable" option, only the first rule is showed

**Comment by g0t4** [comment]
FYI, just stumbled on a 2.3.2 pre-release with vbox 7 support:

https://github.com/hashicorp/vagrant-installers/releases/tag/v2.3.2.dev%2Bmain

**Comment by chrisroberts** [comment]
Hi there. Thanks for this PR! While we really appreciate this PR we are going to close it in favor of a different PR that includes a fix for port forwarding and test coverage. Support for VirtualBox 7.0 was added via #12953 and is included in the latest release (2.3.2). 

Thanks again!

**Comment by scoter-oracle** [comment]
Thank you too @chrisroberts  and thanks for fixing the port-forwarding issue. BTW, the port-forwarding issue was due to a problem with VBox 7.0 CLI (vboxmanage) that didn't properly share forwarded ports. The same is going to be fixed with VirtualBox 7.0.2 release.

**Comment by chrisroberts** [comment]
@scoter-oracle Will there be a 7.0.1 release with it still no properly outputting forwarded ports? There's currently a check to just apply the workaround on VirtualBox 7.0.0 and if a 7.0.1 release is planned I'd like to be sure to get a point release for Vagrant out when it ships so it will work correctly there too. Thanks!

**Comment by scoter-oracle** [comment]
@chrisroberts actually test builds are still there for 6.1.x. But you should see 7.0.2 out in the coming days and that build will have the fix for "Forwarded Ports". I can assure you that this fix is already in-place because I'm playing with an internal build actually and I do not encounter anymore this issue:

```
[scoter@area51: ~]# vboxmanage showvminfo --machinereadable tmp_default_1666211303200_10502 |grep -i forward
Forwarding(0)="ssh,tcp,127.0.0.1,2222,,22"
Forwarding(1)="tcp8080,tcp,,8080,,80"
```
```
[scoter@area51: ~/tmp]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'oraclelinux/9'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'oraclelinux/9' version '9.0.369' is up to date...
==> default: Setting the name of the VM: tmp_default_1666211303200_10502
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 6.1.34
    default: VirtualBox Version: 7.0
==> default: Configuring proxy environment variables...
==> default: Configuring proxy for Yum...
==> default: Mounting shared folders...
    default: /vagrant => /Users/scoter/tmp
```

**Pull request closed without merging**
