### PR TITLE
Fix NFS sharing in macOS 10.15 (based on #11105)

### PR DESCRIPTION
**Pull request by chrisroberts**
This is a continuation of the work started in #11105

The firmlinks defined on the system can be located within
a system file (/usr/share/firmlinks). This can be read to
generate a simple map that can then be used for updating
paths as required.

Added a new host capability (resolve_host_path) which is
used by the bsd host nfs_export capability. The bsd host
implements this capability as a no-op, and the darwin
host implements this capability to handle firmlinks.

### CODE REVIEW

**Comment by andyfowler** [comment]
Thanks, @chrisroberts! Appreciate you running with this. Isolating path resolution from the NFS class definitely feels like a cleaner approach! I saw that `/usr/share/firmlinks` file, and wasn't really sure how authoritative it was, but Apple refer to it, so I assume it's a supported means of decoding firmlinks. 

I tested this branch on the "GM" version of 10.15, and it works great! 🚢 

```
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15
BuildVersion:   19A582a
```

**Comment by vanderlee** [comment]
Any idea on when this fix will become available to the public?

**Comment by briancain** [comment]
Hi @vanderlee - We are currently working on pushing out the next release of Vagrant (2.2.6) as soon as possible. Sorry I don't have an exact date.

**Comment by jakedowns** [comment]
Just tested Vagrant 2.2.6 after seeing https://github.com/hashicorp/vagrant/commit/ae9c3e28d671f9230c18639f452d573914fabee0

i'm getting this error https://cl.ly/f271e8a02b9e

**Pull request merged**
