### PR TITLE
Fix box version sort in Update.update_specific

### PR DESCRIPTION
**Pull request by alex-goncharov-usa**

### CODE REVIEW

**Comment by briancain** [comment]
Hey thanks for the pull request! If you could, please submit some tests too! A simple test ensuring that the proper version is picked when multiple versions exist would be sufficient enough. It would go inside of this context here:

https://github.com/hashicorp/vagrant/blob/master/test/unit/plugins/commands/box/command/update_test.rb#L35

If you want help writing this test please let me know and I'll be happy to provide guidance :+1:

**Comment by briancain** [comment]
Just tested the fix too and it looks good to me and fixes the error :+1:

**Comment by alex-goncharov-usa** [comment]
I did test the fix, as a concept, and then in my real situation, where I knew the buggy behavior from a week's experience.

**Comment by briancain** [comment]
@alex-goncharov-usa ah, sorry. I meant a unit test. If you take a look at that file I linked to, an rspec test would go in there showing that if you invoke the `box update` command, the right version will be selected with your fix. Again, happy to explain a bit or walk you through it if that doesn't make sense!

**Comment by alex-goncharov-usa** [comment]
I'll take a look (which I wanted to avoid :)

**Comment by briancain** [comment]
thanks for the test @alex-goncharov-usa ! I need to head out for the evening but I'll take a look to make sure everything looks good to go and get it merged tomorrow. :tada:

**Comment by alex-goncharov-usa** [comment]
OK, I did what I could, under the circumstances, where I have to leave and had to learn the mechanics of the whole set of Ruby unit test subtleties, `rake` and `bundle` in a very short time.  I decided to extend an existing unit test rather than to write another one.

I could not test it properly since I didn't have time to experiment with `bundle`.

Some of the commands I ran were: 

```
bundle install
cp /usr/local/lib/ruby/gems/2.5.0/bundler/gems/vagrant-spec-abfc34474d12/vagrant-spec.gemspec vagrant-spec.config.rb
bundle exec rake acceptance:components
bundle exec rake acceptance:run COMPONENTS="cli/box"
bundle exec rake acceptance:run COMPONENTS="cli/plugin"
``` 
I couldn't wait for the last one to complete.  If you can teach me what to do for this task, it might prove useful.  

Thanks!

**Comment by briancain** [comment]
@alex-goncharov-usa - looks good to me! Modifying that test is fine I think.

For next time, you can run rspec directly on test files rather than the whole unit test suite. Something like....

```
brian@localghost:vagrant % be rspec test/unit/plugins/commands/box/command/update_test.rb                                                                                                                                        ±[●][master]
Run options: exclude {:windows=>true}

VagrantPlugins::CommandBox::Command::Update
  execute
    updating specific box
      doesn't update if they're up to date
      does the correct update if there is an update
      raises an error if there are multiple providers
      with multiple providers and specifying the provider
        updates the proper box
        raises an error if that provider doesn't exist
      download options are specified
        passes down download options
      with a box that doesn't exist
        raises an exception
    updating environment machines
      ignores machines without boxes
      doesn't update boxes if they're up-to-date
      boxes have an update
        updates boxes
        when box version is updated but previous box exists
          updates the box
        machine has download options
          uses download options from machine
          download options are specified on the command line
            overrides download options from machine with options from CLI
          force flag is specified on the command line
            passes force through to action_box_add as true

Finished in 1.2 seconds (files took 0.39115 seconds to load)
14 examples, 0 failures
```

Thanks for the pull request and updating with a test! It should be out in the next release of Vagrant.

**Comment by alex-goncharov-usa** [comment]
Thank you for the tip, Brian: your suggestion worked for me like magic!

**Pull request merged**
