### PR TITLE
Update configure_disks.rb

### PR DESCRIPTION
**Pull request by camillo-toselli**
fixed configure_disks.rb in hyper-v capabilities provider to allow creation and removal of additional disks,

### CODE REVIEW

**Comment by camillo-toselli** [comment]
Added double splat to created_disk and attach_disk invocations to explicitly allow  the implicit conversions disabled in Ruby 3.x.
This fix makes the creation and removal of disks by the hyper-v provider start working again.

**Comment by camillo-toselli** [comment]
Dear mantainers,

can we proceed with workflows approval? can you enable me to run workflows needed for final review?
These simple changes make hyperv disk configuration work correctly also on Ruby 3.xx.
Thanks in advance,

Best regards.

Camillo

**Comment by camillo-toselli** [comment]
Dear Paul - Thank you. Have you any news about any incoming review?

**Comment by PaulNacamuli** [comment]
No.  I'm not a maintainer, just a user.

**Review by chrisroberts — APPROVED** [review]
:+1:

**Comment by chrisroberts** [comment]
Thanks for this PR and my apologies for the delay in getting reviewed and merged!

**Comment by camillo-toselli** [comment]
Thank you so much!

Camillo

**Pull request merged**
