### PR TITLE
doc-fix dont escape  $

### PR DESCRIPTION
**Pull request by ArjunDandagi**
dont escape expanding $VAR in shell

### CODE REVIEW

**Comment by ArjunDandagi** [comment]
@soapy1 @jbonhag 
Thanks a lot for approving the PR , 

I am a beginner in OSS contribution ( this is my second doc fix in hashicorp :smile: ) 
I would like to take your help on contributing to hashicorp stack with coding . could you help me please .

TIA
- Arjun

**Comment by jbonhag** [comment]
Hi @ArjunDandagi,

Sure! Is there a particular issue that you're interested in working on?

**Comment by ArjunDandagi** [comment]
I am completely new to ruby, i am ready to learn it .want to learn by contributing directly 
can you point me to some work/ beginner guide on how to pick issues and work on them. or may be guide me to 
small issue in this project itself :smile:

TIA
- Arjun

**Comment by jbonhag** [comment]
Hey @ArjunDandagi,

I'd start by reviewing the [Vagrant contribution guidelines](https://github.com/hashicorp/vagrant/blob/master/.github/CONTRIBUTING.md). Next, look through the open issues for Vagrant to find one that sounds interesting. Some issues are tagged with the [task-small](https://github.com/hashicorp/vagrant/labels/task-small) label, which would be good candidates for a first PR. You can initiate a conversation directly from the issue if you see something that you'd like to work on. Once you've opened a PR, we're more than happy to review and provide feedback on it.

Good luck, and thanks for contributing to Vagrant!

**Pull request merged**
