### PR TITLE
Support Windows Salt Minions greater than 2016.x.x

### PR DESCRIPTION
**Pull request by jonlabroad**
This is a fix for #8925 

The latest version of the Windows Salt Minion could not be used because Salt added the Python version to the filename, therefore the Salt provisioner could not find the minion installer.

The Python version is added to the filename if the version is >= 2017.x.x. The Python version can be changed using the python_version parameter (default=2).

Additionally, the Salt provisioner was adding Linux-only bootstrap script parameters to the Powershell script. The expected behavior is that the Linux-only parameters are ignored and not passed into the Powershell script at all.

### CODE REVIEW

**Comment by jonlabroad** [comment]
Hi @briancain , I finally got around to adding those tests you requested.

**Comment by fzk-rec** [comment]
When will a new Vagrant version be released? We run 2.0.0 and hit this exact issue :(

**Comment by jonlabroad** [comment]
@fzk-rec 
In the meantime, a decent workaround is making a copy of the script (https://github.com/hashicorp/vagrant/blob/master/plugins/provisioners/salt/bootstrap-salt.ps1) and running it after the Salt provisioner:
`config.vm.provision "shell", path: "bootstrap-salt.ps1", args: "-Version 2017.7.1"`

**Comment by briancain** [comment]
Hi @fzk-rec - we are planning for a release early next week!

**Comment by fzk-rec** [comment]
Thx for the info guys!

**Pull request merged**
