### PR TITLE
[WIP] Change `mkdir` command on Windows for rsync

### LINKED ISSUE #11878: Rsync to a Windows guest fails if the target diretory already exists.
I'm having an issue with rsync from a Linux host to a Windows 2019 guest (using the `libvirt` provider, although I don't think that's a factor).

The first time I rsync, everything works great.  However after that first time, the target directory exists, and all subsequent rsync operations fail with a pretty straightforward error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p 'C:\Users\Administrator\elastio'

Stdout from the command:




Stderr from the command:

#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">mkdir : An item with the specified name C:\Users\Administrator\elastio already exists._x000D__x000A_</S><S S="Error">At line:1 char:183_x000D__x000A_</S><S S="Error">+ ... -13873d338b86-vagrant-ssh');mkdir -p 'C:\Users\Administrator\elastio'_x000D__x000A_</S><S S="Error">+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ResourceExists: (C:\Users\Administrator\elastio:String) [New-Item], IOException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
```

I can confirm that if I use `vagrant ssh` to SSH into this Windows box, and I run the Powershell command `mkdir -p 'C:\Users\Administrator\elastio'`, that also fails with the same error.  This is, unfortunately, expected behavior on Powershell; `mkdir -p` doesn't mean the same thing as it does in Unix systems.  The `-p` is taken to mean `-Path`.  The correct form on Powershell to create a directory and any missing parent directories, but not fail on error, is `mkdir -Force`.

The Vagrant code was modified as a part of the fix for #6115 to use `mkdir -p` instead of `mkdir`.  I am surprised that worked on Windows at the time the fix was made a few years ago.  It definitely doesn't work now, at least with the latest Powershell on Windows 2019.

### Vagrant version

```
Installed Version: 2.2.9
```

### Host operating system

Fedora 32

### Guest operating system

Windows 2019

### Vagrantfile

Unfortunately we use an internal Vagrant box for Windows that I'm unable to share.

Here's the relevant rsync config:

```ruby
config.vm.define "#{box}", autostart: false do |b|
  # ...
  b.vm.synced_folder "../", "C:\\Users\\Administrator\\elastio", type: "rsync", rsync__args: ["-rLkz", "--delete", "--filter=:- .gitignore"], rsync__exclude:[".git/", ".vagrant/"], disabled: false
  # ..
end

```

We use the WinSSH communicator.

### Debug output

https://gist.github.com/anelson/14ea1c80b00c01b60b8490f9575c5c5b

### Expected behavior

All `vagrant rsync` operations should succeed, whether the target exists or not.

### Actual behavior

`vagrant rsync` fails with an error if the target directory exists (in other words, it fails all but the first time rsync is invoked):

```
==> windows2019-amd64-build: Rsyncing folder: /home/cornelius/projects/elastio/elastio/ => /cygdrive/C\\Users\\Administrator\\elastio
==> windows2019-amd64-build:   - Exclude: [".vagrant/", ".git/"]
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p 'C:\Users\Administrator\elastio'

Stdout from the command:




Stderr from the command:

#< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">mkdir : An item with the specified name C:\Users\Administrator\elastio already exists._x000D__x000A_</S><S S="Error">At line:1 char:183_x000D__x000A_</S><S S="Error">+ ... -13873d338b86-vagrant-ssh');mkdir -p 'C:\Users\Administrator\elastio'_x000D__x000A_</S><S S="Error">+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ResourceExists: (C:\Users\Administrator\elastio:String) [New-Item], IOException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
```

### Steps to reproduce

1. Start with a Windows 2019 guest with `rsync` configured and enabled.
2. Run `vagrant up`, which will automatically perform an rsync
3. Run `vagrant rsync` again; it will fail because the rsync target exists.

### References

- #6115 (The fix for this issue changed the `mkdir` command to the form that's failing now)
- #8588 (The PR in which the `mkdir` command was changed

### PR DESCRIPTION
**Pull request by anelson**
This corrects the `mkdir` command used by rsync on Windows to make sure
the destination directory exists before starting to sync.  The old form
was correct on Linux but not on Windows, and it was just a coincidence
that the `-p` argument appeared to be work.

Please note that I am completely unfamiliar with the Vagrant codebase, so I am not sure how to properly test this.  The bug appears to be serious enough that it should always fail, at least on newer Powershell versions (I haven't tried to reproduce on any guest other than Windows 2019 with Powershell 7).

I use the patch herein on my local development system to fix this issue; that is as much testing as this patch has undergone so far.

Closes #11878

### CODE REVIEW

**Comment by anelson** [comment]
Hey @chrisroberts sorry if you're not the right person to tag for this, you were the one who merged the PR which changed this source file last time.  If this is better addressed to someone else I'd appreciate if you pointed me in the right direction.

**Comment by e-kov** [comment]
@anelson could you please undraft your PR?

@soapy1 could you please review this useful fix?

**Comment by e-kov** [comment]
Ah, I see, `Only those with write access to this repository can mark a draft pull request as ready for review.`
@soapy1 maybe you can help find someone to review this PR...

**Comment by e-kov** [comment]
@chrisroberts could you please review and merge this PR? We really need this fix. More than 1 year already passed since this PR has been submitted...

**Review by chrisroberts — APPROVED** [review]
Thanks!

**Comment by e-kov** [comment]
:tada: :tada: :tada: 
Thank you, Chris!

**Pull request merged**
