### PR TITLE
Get folder mount name

### PR DESCRIPTION
**Pull request by soapy1**
fixes https://github.com/hashicorp/vagrant/issues/12277

additional tests in the vagrant-spec project https://github.com/hashicorp/vagrant-spec/blob/main/acceptance/synced_folder/smb_spec.rb

### CODE REVIEW

**Review by chrisroberts — CHANGES_REQUESTED** [review]
We should also update the test for this by updating the allow mock to only match on the correct number of passed arguments.

**Comment by DanSibbernsen** [comment]
Hi! I'm relatively new to the Vagrant world. Would this fix also need to be incorporated into the Vagrant-Parallels provider's use of mount? Example [here](https://github.com/Parallels/vagrant-parallels/blob/8ac0b2bae6428bfb485f25b59f224444fe317014/lib/vagrant-parallels/cap/mount_options.rb#L33)?

If so, I can open a change request over there (I'm stuck on this issue too)

**Comment by soapy1** [comment]
@DanSibbernsen yep, I think you are right. That `mount_name` bit should look something like [this smb capability](https://github.com/hashicorp/vagrant/blob/main/plugins/synced_folders/smb/cap/mount_options.rb#L48). You can double check that this change is required by running vagrant 2.2.15 with the parallels plugin.

**Review by chrisroberts — APPROVED** [review]

**Comment by legal90** [comment]
Thank you, @soapy1.  
It's a bit unfortunate that the positional arguments passed to `mount_name` capability were changed in Vagrant 2.2.15 (by https://github.com/hashicorp/vagrant/pull/12281). That was a breaking change for 3rd party plugins like `vagrant-parallels`, implementing this capability on their side. :(

We have to use some smelly hacks in order to work it around and keep the backward compatibility: https://github.com/Parallels/vagrant-parallels/pull/386

**Pull request merged**
